version: '3.9'

services:
  dashy:
    image: lissy93/dashy:2.1.1
    container_name: dashy-app
    volumes:
      - $(pwd)/conf.yml:/app/public/conf.yml:ro
      - $(pwd)/data:/data:ro
    ports:
      - '80:80'
    networks:
      - dashy-net
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s

networks:
  dashy-net:
    name: dashy-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
