version: "3.8"

services:
  dashy:
    image: lissy93/dashy:2.1.1
    container_name: Dashy
    # - /root/my-config.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 0s
