version: '3.9'

services:
  dashy:
    image: lissy93/dashy:2.1.1
    volumes:
      - $(pwd)/conf.yml:/app/public/conf.yml
    networks:
      - dashy-net
    environment:
      - NODE_ENV=production
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

networks:
  dashy-net:
    name: dashy-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
